### ISSUE TITLE
Implement translation of shared expressions in the backend

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#104]
## Description

Shared expressions in the lifted IR should be translated to Coq code using the `share` operator. 

## Motivation

Any time a variable is shared in Haskell, it should also be shared in Coq, even in the presence of effects. Since Coq does not support sharing natively, shared expressions and variables must be shared explicitly using the `share` operator in the generated Coq code.

## Dependencies

This issue depends on the representation of sharing in the IR, so it can only be worked on when we have an appropriate construct in the (lifted) IR.

## Additional Context

This issue is a duplicate of #176 and will therefore be closed.

**Comment by nbun** [comment]
This is still to be discussed, but with the new lifted IR, I think the transformation of shared expressions into an explicit sharing operator can be integrated as part of the `Free` lifting from the IR to the lifted IR. In particular, this transformation would translate `let` expressions into a combination of `share` and `(>>=)`.

**Comment by MajaRet** [comment]
This issue is a duplicate of #176 and has therefore been closed.
