### ISSUE TITLE
Implement effect combinator and effects for sharing and non-determinism in Coq

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#109]
## Description

The following effects should be implemented in Coq:
- A `Comb` effect representing the combination of two effects.
- A `Share` effect representing sharing using a state and explicit scoping tags.
- An `ND` effect representing a non-deterministic program.

## Motivation

In order to model sharing in Coq, we must be able to mark sharing scopes and assign IDs to shared expressions so that a handler can correctly identify shared expressions and handle them accordingly. For this, we need a `Share` effect that contains a state and tags to open and close scopes.

Because we need to combine the `Share` effect with the other effect(s) of the program, we also need a combinator `Comb` for effects. 

The `ND` effect models a non-deterministic program. Non-determinism is an effect where sharing (call-time choice) has to be modeled explicitly, so this effect is useful to test our implementation of sharing.

**Comment by ichistmeinname** [comment]
What about tracing? We  could even add the translation for Haskell's `trace`-function to test the code generation. Non-determinism on the other hand won't be part of the Haskell front end, right? ; )

**Comment by MajaRet** [comment]
That's true. Non-determinism _is_ certainly useful to test our implementation of sharing, though. We can also give generated code non-deterministic arguments. And I suppose it'll be useful if we ever add a Curry front end : D

I'll look into adding a tracing effect!
