### ISSUE TITLE
AST for Agda

### ISSUE THREAD

**Issue by ichistmeinname** [FreeProving/free-compiler#17]
Similar to the `language-coq` package that contains the AST definitions, parser and "pretty"-printer for the Coq backend, we need a similar package for the Asda backend.

* [ ] search for a `language-agda` package that is already available in the Haskell ecosystem
* [ ] (optional, depends on other options) checkout the Agda compiler for a AST implementation and ask for a separate package
* [ ] (optional, depends on other options) outsource the necessary parts form the Asda compiler to its own package

**Comment by JonasHoefer** [comment]
A separate AST package does not seem to exist. The Agda compiler has it's  [own internal AST](https://github.com/agda/agda/tree/master/src/full/Agda/Syntax).

**Comment by JonasHoefer** [comment]
Since we decided to use the AST from the Agda compiler, can we close this Issue?
