### ISSUE TITLE
Compiler installation fails with cabal 2.4.0.0

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#2]
The installation of the compiler via `cabal new-install freec` fails with the following message:
`Wrote tarball sdist to 
~/free-compiler/dist-newstyle/sdist/free-compiler-0.1.0.0.tar.gz`
`cabal: The impossible happened: a local package isn't local`
when I use cabal version 2.4.0.0.
Upgrading to cabal 3.2.0.0 fixes the problem.

The GHC version is 8.6.5.

**Comment by ichistmeinname** [comment]
Might be related to https://github.com/haskell/cabal/issues/5643.

**Comment by just95** [comment]
I've just installed Cabal 2.4.0.0 locally and can confirm, that the `new-install` command is in fact broken in that version. Until now I have been using version 2.4.1.0 on my machine and in the CI pipeline. I've updated the documentation to clarify that the compiler has been tested with version 2.4.1.0 only. Of course you can continue using 3.2.0.0 if that version works. Unfortunately, I'll not be able to test 3.2.0.0 automatically as the latest version currently available in GitHub actions is 3.0.0.0.

**Comment by ichistmeinname** [comment]
@MajaRet Can you modify the cabal-version specified in free-compiler.cabal to 2.4.1.0? Please check Justin's contributing guide ([CONTRIBUTING.md](https://github.com/FreeProving/free-compiler/blob/master/CONTRIBUTING.md#how-can-i-contribute)) beforehand.

**Comment by ichistmeinname** [comment]
As far as we checked, we cannot annotate the exact cabal-version.
