### ISSUE TITLE
Main functions are wronly inlined as well

### ISSUE THREAD

**Issue by jo-hanna1997** [FreeProving/free-compiler#57]
### Description

When a function `f` calls another function `g` for which (as expected) no corresponding helper function `g_0` exists inlining is still performed using `g` which leads to type errors.

### Steps to Reproduce

Compile the following Haskell module.

```haskell
module Left where

data Tree a = Leaf a | Node (Tree a) (Tree a)

{-# FreeC left DECREASES ON ARGUMENT 1 #-}
--left and left' are mutually recursive
left :: Tree Bool -> Bool
left t = left' t

left' :: Tree Bool -> Bool
left' (Leaf n    ) = n
left' (Node t1 t2) = left t1

--goLeft is an entry function into the mutual recursive circle
goLeft :: Tree Bool -> Bool
goLeft (Leaf n    ) = n
goLeft (Node t1 t2) = left t1
```

#### Expected behavior

The function `left` should simply be called on a the monadic argument.

```coq
Definition goLeft (Shape : Type) (Pos : Shape -> Type) (a7
    : Free Shape Pos (Tree Shape Pos (Bool Shape Pos)))
   : Free Shape Pos (Bool Shape Pos) :=
  a7 >>=
  (fun a7_0 =>
     match a7_0 with
     | leaf a8 => a8
     | node a10 a11 => left Shape Pos a10
     end).
```

#### Actual behavior

The `goLeft` function wrongly tries to inline `left`

```coq
Definition goLeft (Shape : Type) (Pos : Shape -> Type) (a7
    : Free Shape Pos (Tree Shape Pos (Bool Shape Pos)))
   : Free Shape Pos (Bool Shape Pos) :=
  a7 >>=
  (fun a7_0 =>
     match a7_0 with
     | leaf a8 => a8
     | node a10 a11 =>
         a10 >>= (fun (a10_0 : Tree Shape Pos (Bool Shape Pos)) => left Shape Pos a10_0)
     end).
```

### Versions

 - Git commit: 87ab7e5f5b74302d44e740c5ed2e19ce959bc9bf
 - `ghc --version`: 8.6.5
 - `cabal --version`: 3.2.0.0
 - `coqc --version`: 8.9.0
 - OS: Windows 10

**Comment by just95** [comment]
As far as I can tell, this issue occurs because the decreasing argument entry that is inserted by the pragma for `left` is not reset correctly. This should be fixed automatically once #41 is merged.
