### ISSUE TITLE
Add support for heterogenous compiler passes

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#72]
## Description

Compiler passes should be able to change the type of processed modules.

## Motivation

Currently a compiler `Pass` is a function of type `a -> Converter a`. The type variable `a` is usually instantiated with `IR.Module`. The idea is now to make passes functions of type `a -> Converter b` . We will refer to passes with different argument and return types as *heterogeneous compiler passes*.

One application of such heterogeneous passes is dependency analysis. Currently, dependency analysis has to be performed both in the passes and in the back end because the information about strongly connected components cannot be preserved in `IR.Module`s. In #71, modules will be parameterized over their content data type. This will allow us to write the `DependencyAnalysisPass` as a heterogeneous pass of type `IR.Module -> Converter (IR.ModuleOf [DependencyComponent IR.TopLevelDecl])`. With this new type, information from the compiler passes can be passed to the back end.

The same technique could be used to encode on type level the assumption that types are annotated after type inference in the future.

## Drawbacks

Since all compiler passes have the same type, they can currently be stored in a list (see [`FreeC.Pipeline`](https://github.com/FreeProving/free-compiler/blob/1b666387fe35fca42652471b6e46c8d3f1305c03/src/lib/FreeC/Pipeline.hs#L25)). This will not be possible in the presence of heterogeneous passes. Some kind of type aligned sequence would have to be used if we still want to represent passes as data. Thus, it is probably best to just combine passes using `(>=>)` for now.

**Comment by JonasHoefer** [comment]
Just as a side note. The definition of a _heterogeneous compiler pass_ is an arrow in the Kleisli category of the `Converter` monad and therefore is equivalent to [`Kleisli`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Arrow.html#v:Kleisli) for `Converter`. If the compiler pipeline becomes more complex (e.g. optional stages based on the choice of backend, splitting and rejoining phases, reusing outputs, ...) we could consider using the `Arrow` instance to avoid writing composition boiler plate code (and maybe write down the pipeline in a more declarative way).
